title: TENTANG
url: "http://basyiri.my.id"
baseurl: "/id"

footer: yes
footer_url: "https://basyiri.my.id/"
footer_text: "Azhar Basyiri Hartono"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "https://basyiri.my.id/id/resume"
 - name: "Kontak"
   link: "https://basyiri.my.id/id/kontak"
